[package]
name = "rkb2040-proc"
version = "0.1.0"
edition = "2024"

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
